### PR TITLE
Code clean up and move Global functions/vars to local

### PR DESCRIPTION
**Pull request by rdelian**
Hi, 

I've changed clean up the code a bit, removed empty lines or the ones with only spaces, removed spaces after end-of-line, and also localize some global variables and functions

### CODE REVIEW

**Comment by HugoSimoes12345** [comment]
this is to change the resources needed for the script to work? like to make the script lighter on the pc?
Thanks for your support, for now i dont have time to try the modifications you made but i will give it a try when i can.

**Comment by rdelian** [comment]
No, it doesn't affect the run-time, it's just cleaner. And I made vars + functions `local` because you don't use them in other files so there is no need for these to be global.

**Comment by rdelian** [comment]
I also moved all variables to a table for an easier way to access the data inside your script from other scripts using exports like so
```lua
-- lets say we wanna stop the manual mode if we start a race
if GetResourceState('HRSGears') == 'started' then
    if exports.HRSGears:Status().manualon then
        ExecuteCommand('manual')
    end
end
```

**Comment by HugoSimoes12345** [comment]
ok man, i will check it when i got some free time to open fivem, add me on discord 
hugo.simoes.12345#4946

its always cool to have a programer friend.

**Pull request closed without merging**
